### ISSUE TITLE
Gringotts-Towny takes my gold but doesnt depoist it with /t depoist

### ISSUE THREAD

**Issue by 22Conner** [nikosgram/gringotts-towny#4]
https://user-images.githubusercontent.com/108838947/196292623-31d16366-f7f7-4880-98a4-8a22fd785888.mp4

**Comment by nikosgram** [comment]
Looking into it :)

**Comment by x390** [comment]
Having the same issue with creating a new town. Takes the gold then says you can't afford to settle a new town.

**Comment by spikehidden** [comment]
I have the same issue and I assume it is the answer time of Gringrotts?
I mean I actually have no clue but I noticed that if you really have no money the message "*There is not enough money in the bank.*" comes a lot quicker.

Or maybe it has to do with Towny's changes of der CancelationEvent. I don't know.

Interesting is though that the bankhistory gets updated on withdrawal but of course you don't get anything the money is just gone.

Taxes and Upkeep payment also seems to work so it seems not to have an issue of retrieving the amount that is stored in the vaults.

As this seems to be an issue only on the player interaction side could it be that this might be a bug on Towny's side with the interaction with vault? Unless of course you bypass Vault and interact with Towny's API directly for player economy interactions.

I wonder if it might had to do with the Towny Addon Plugins (SiegeWars, TownyResources). I doubt it though. But when I tested that I come back.


*Whatever, I hope my thoughts help. Probably not. 😅*

P.S.: Also effects `/n deposit|withdraw {$}`

**Comment by spikehidden** [comment]
***(Possible "Workaround" at the end.)***

I don't know if it helps but the following things seem to affected or not:

#### Affected

- Town Creation
- Nation Creation
- Town/Nation Withdrawing
- Town/Nation Depositing

#### Unaffected

- Taxes
- Upkeep

Also the mentioned Plugins do not cause this issue.

### Cause?
***As of writing this I was testing around and I'm 99% sure to have found what the issue is.***\

If you set `economy.closed_economy.enabled` to true and try to put a nation or town account at `economy.closed_economy.server_account` the problem appears but if I put a player in there or an account that cannot exist it does not happen.

**Ex.:**

```yml
economy:
  closed_economy:
    server_account: town:my_town
    enabled: 'true'
```
I assume that Gringotts doesn't answer when Towny tries to check that account? idk 🤷‍♂️

### Workaround

Well for anyone reading this because they have the same issue deactivate the feature or use it with a (fake) player.
You could also create a fake player by deactivating online-mode joining with a player that starts with `#` and then restart your server with activated online-mode. There you have your fake player account that works with Gringotts.

**Comment by brandcrystal** [comment]
Any update on this fix? Really wanting to use this, thanks.

**Comment by ponkersboard** [comment]
any update? @nikosgram I want to use gringotts with towny but this makes it unusable :)

**Comment by GroobleDierne** [comment]
Do you get an error in the console?

**Comment by JuniperTree4Me** [comment]
> 

Separate person, same issue, yes I do. (See image attached)

It's "java.lang.BoClassDefFoundError: org/gester/gringotts/api/dependency/Dependency"
Searching through the .jar, I see no reference to that in the "org" folder.

![image](https://user-images.githubusercontent.com/130091751/230461612-4fcb7d56-bb21-4e7c-897d-aa75a2e51acd.png)

**Comment by Nicheven** [comment]
I am also having this issue, rendering this plugin both useless and frustrating. 

24.05 04:16:21 [Server] ERROR Could not load plugin 'gringotts-towny-2.12.4-SNAPSHOT.jar' in folder 'plugins'
24.05 04:16:21 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
24.05 04:16:21 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
24.05 04:16:21 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO ... 9 more
24.05 04:16:21 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.gestern.gringotts.api.dependency.Dependency
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO ... 9 more
24.05 04:16:21 [Server] ERROR ebean.properties not found
24.05 04:16:21 [Server] INFO DataSourcePool [Gringotts] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
24.05 04:16:21 [Server] INFO SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
24.05 04:16:22 [Server] INFO Entities enhanced[0] subclassed[2]

**Comment by GroobleDierne** [comment]
> > 
> 
> Separate person, same issue, yes I do. (See image attached)
> 
> It's "java.lang.BoClassDefFoundError: org/gester/gringotts/api/dependency/Dependency" Searching through the .jar, I see no reference to that in the "org" folder.
> 
> ![image](https://user-images.githubusercontent.com/130091751/230461612-4fcb7d56-bb21-4e7c-897d-aa75a2e51acd.png)

Are you sure you installed both Gringotts-towny and Gringotts ?

**Comment by nikosgram** [comment]
It might be the case that Gringotts is not part of the plugins. Gringotts-Towny requires both Gringotts and Vault to properly function. 

Can you verify that both of those plugins are part of your plugins?

**Comment by JuniperTree4Me** [comment]
Yes, both plugins are installed and exist in the plugins folder. The server
is offline until everything is updated for 1.20, however when it goes back
online I do hope to use Vault/Towny/Gringotts if possible.

**Comment by Asuniia** [comment]
same issue in 1.20.1

**Comment by nikosgram** [comment]
Is it possible to reproduce it with the latest version of Gringotts? :) If you haven't already.

**Comment by ponkersboard** [comment]
> We currently waiting for 1.20 ecosystem to get a bit robust before we decide to start supporting it. Although, feel free to give it a try and report any issues. :)
> 
> BTW, A full list of the plugins installed, if possible, would be incredible helpful.

this got forgotten or no?
@nikosgram

**Comment by ponkersboard** [comment]
There is no issue in console
and the money just dissapears
PLEASE!! FIX ASAP
