### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by adabugra** [nikosgram/gringotts-towny#6]
[19:37:08] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'gringotts-towny-2.12.4-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:275) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.gestern.gringotts.api.dependency.Dependency
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	... 9 more

**Comment by Nicheven** [comment]
Adding mine as well for visibility

`24.05 04:16:21 [Server] ERROR Could not load plugin 'gringotts-towny-2.12.4-SNAPSHOT.jar' in folder 'plugins'
24.05 04:16:21 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
24.05 04:16:21 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/gestern/gringotts/api/dependency/Dependency
24.05 04:16:21 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO ... 9 more
24.05 04:16:21 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.gestern.gringotts.api.dependency.Dependency
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
24.05 04:16:21 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
24.05 04:16:21 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
24.05 04:16:21 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-538]
24.05 04:16:21 [Server] INFO ... 9 more
24.05 04:16:21 [Server] ERROR ebean.properties not found
24.05 04:16:21 [Server] INFO DataSourcePool [Gringotts] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
24.05 04:16:21 [Server] INFO SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
24.05 04:16:22 [Server] INFO Entities enhanced[0] subclassed[2]`

**Comment by nikosgram** [comment]
Hi there!

It appears that Gringotts is absent. For Gringotts Towny to function, Gringotts is required as it holds all the essential functionalities. Gringotts Towny essentially provides Towny support.

Feel free to download it from Spigot at the following link:

https://www.spigotmc.org/resources/gringotts.42071/

❤️
